server:
    port: 0
spring:
    application:
        name: EmailNotificationMicroservice
    kafka:
        consumer:
            bootstrap-servers: localhost:9092,localhost:9094
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            group-id: product-create-events
            properties:
              spring:
                  json:
                      trusted:
                          packages: aleksey.emailnotificationmicroservice.kafka_consumer.model
            isolation-level: read_committed
